name: GitHub Actions Demos
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: /tmp/actions-runner/_work/filenotexist
      - run: git clone https://github.com/quentinlrx/aws-iac.git 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd aws-iac
      - run: terraform plan
      - run: terraform apply
